apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: atplcrm-keyvault
  namespace: atplcrm
spec:
  provider: azure

  secretObjects:
    - secretName: atplcrm-secret
      type: Opaque
      data:
        - objectName: APP-SECRET
          key: APP_SECRET
        - objectName: POSTGRES-PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: DEMO-PASSWORD
          key: DEMO_PASSWORD

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "7e838f36-1f40-424e-b912-7d8246531f01"
    keyvaultName: "crmkey"
    tenantId: "3ad7ab73-4c91-4d09-a567-1e747a70c126"
    objects: |
      array:
        - |
          objectName: APP-SECRET
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
        - |
          objectName: DEMO-PASSWORD
          objectType: secret
